require 'test/unit'
load './mdiff.rb'

class MdiffTest < Test::Unit::TestCase

=begin
All arguments and ground-truth values are generated by python version.
=end

  def test_linesplit()
    text = "27fd1696c44a1476436abb36e60cb915084d9cef\nlanfengxiang@lanfengxiangdeMacBook-Pro.local\n1542493451 18000\nHello\n\ncommit\n\n"
    res = Mdiff.linesplit(text)

    gt = ["27fd1696c44a1476436abb36e60cb915084d9cef\n", "lanfengxiang@lanfengxiangdeMacBook-Pro.local\n", "1542493451 18000\n", "Hello\n", "\n", "commit\n", "\n"]
    assert_equal(gt, res)
  end

  def test_textdiff()
    a = "27fd1696c44a1476436abb36e60cb915084d9cef\nlanfengxiang@lanfengxiangdeMacBook-Pro.local\n1542493451 18000\nHello\n\ncommit\n\n"
    b = "126e0d9c1f98a8c5c37f227202eb5b415c3f3911\njshi@dhcp-10-4-13-195.wireless.rochester.edu\n1542644657 18000\nbar.txt\nfoo.txt\n\ncommit\n"
    res = Mdiff.textdiff(a, b)

    gt = "\x00\x00\x00\x00\x00\x00\x00m\x00\x00\x00w126e0d9c1f98a8c5c37f227202eb5b415c3f3911\njshi@dhcp-10-4-13-195.wireless.rochester.edu\n1542644657 18000\nbar.txt\nfoo.txt\n\x00\x00\x00u\x00\x00\x00v\x00\x00\x00\x00"
    assert_equal(gt, res)
  end

  def test_patch()
    b = "\x00\x00\x001\x00\x00\x001\x00\x00\x0014765e17b3849483d3431376e77ff781367a3a472 foo.txt\n"
    text = "c72fcb0d3de9d0bfac631a6dca71578f95667c76 bar.txt\n"
    res = Mdiff.patch(text, b)

    gt = "c72fcb0d3de9d0bfac631a6dca71578f95667c76 bar.txt\n4765e17b3849483d3431376e77ff781367a3a472 foo.txt\n"
    assert_equal(gt, res)
  end
end